### ISSUE TITLE
Extend customer functionality

### ISSUE THREAD

**Issue by avoelkl** [magento-hackathon/Magento-Two-factor-Authentication#16]
1. Adding the possibility for the customer to reset 2FA.
2. Add security questions for customer
3. Info field for customers to activate 2FA

**Comment by avoelkl** [comment]
No. 3 solved by 1d9a428000a21e6978abcb07bf6ace6d949c34ce

**Comment by avoelkl** [comment]
No. 1 solved by b9ef8356cdb8af0c391c205a87a20037f62a27aa

**Comment by avoelkl** [comment]
Are security questions + answers (which need to be stored extra) are a benefit for a customer? Any opinions on that?

**Comment by melvyn-sopacua** [comment]
I was thinking about it...You want people to transition to 2FA. If you bombard them with too many options, they will bail out. It's better to require one part, then show a "x% of security features enabled" horizontal bar graph, same thing you see with "% completed of profile" on invasive sites like LinkedIn :p.

**Comment by gfobe** [comment]
For backend users it's important to have at lease one security questions because otherwise (when you lost your device or something else) you are not able to login into your store anymore. A frontend user can always be configured by a backend user so here it's not so important I think. But it will be wise to place a customer support link in the near if frontend user has problems and want to do the shopping.

**Comment by avoelkl** [comment]
I think so too: It might keep customers away from activating 2FA if it looks too complicated.
Dropbox for example provides a second backup via SMS.
For now I think it's fine if admin users can reset the 2FA for customers and we add some information to contact the customer support.

The feature @melvyn-sopacua mentioned is nice, would be a nice PR ;)

**Comment by gfobe** [comment]
@avoelkl can you please check, that backend users can not only reset the tokens (so that frontend user can register to 2FA again) but also that backend users can disable 2FA for a customer?

**Comment by avoelkl** [comment]
Good point @gfobe. I've extended the functionality. Resetting from admin panel makes no sense anyway as you have to be logged-in to set it again.
It's now a reset + disable.
