### ISSUE TITLE
Magento 2 version?

### ISSUE THREAD

**Issue by cscd98** [magento-hackathon/Magento-Two-factor-Authentication#34]
I'm thinking of adding this to our Magento 1 store but we also plan to move to M2 this year. Is there a version available for m2?

**Comment by avoelkl** [comment]
Hi,
There is no M2 version and given, that this extension was developed during several Magento Hackathons it might as well take some time and effort until there is a new version again.

The only Two Factor Authentication for Magento 2 I am aware of (currently) is this one:
https://marketplace.magento.com/xtento-twofactorauth.html

**Comment by cscd98** [comment]
@avoelkl Thank you
